stages:
  - test
  - deploy

cache:
  paths:
    - node_modules/

lint:
  stage: test
  image: node:16-alpine3.14
  only:
    - merge_requests
  script:
    - yarn install
    - yarn lint

ssh:
  stage: deploy
  only:
    - merge_requests
  before_script:
    - 'which ssh-agent || ( apk update && apk add openssh-client )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - ssh-keyscan -H $SSH_SERVER_IP >> ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/known_hosts
  script:
    - >
      ssh -t -t $SSH_SERVER_USER@$SSH_SERVER_IP
      "cd ${PATH_TO_PROJECT};
      git pull origin develop;
      docker-compose up -d;
      "
